### ISSUE TITLE
ADC not loading

### ISSUE THREAD

**Issue by martykube** [pgmmpk/beaglebone_pru_adc#5]
Hi Mike

I've been trying to get the wheel encoders to work.  I've gotten to the point where, yeah, I think we need the PRU :-)

Your code looks great.  The install seemed to work fine.  I ran the first example and ran into the issue below.

I'm looking into it.  I think this is going to be an python file.open() on the sysfs tree maybe.  IDK...

Marty

```
<examples> uname -a
Linux beaglebone 3.8.13-bone47 #1 SMP Fri Apr 11 01:36:09 UTC 2014 armv7l GNU/Linux
<examples> pwd
/home/debian/beaglebone_pru_adc/examples
<examples> ls
basic.py  encoders.py  encoders_test.py  oscilloscope.py  speed_control.py  speed.py  thresholds.py
<examples> sudo cat /sys/devices/bone_capemgr.9/slots 
 0: 54:PF---
 1: 55:PF---
 2: 56:PF---
 3: 57:PF---
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
 7: ff:P-O-L Override Board Name,00A0,Override Manuf,am33xx_pwm
 8: ff:P-O-L Override Board Name,00A0,Override Manuf,bone_pwm_P9_16
 9: ff:P-O-L Override Board Name,00A0,Override Manuf,bone_pwm_P9_14
10: ff:P-O-L Override Board Name,00A0,Override Manuf,cape-bone-iio
11: ff:P-O-L Override Board Name,00A0,Override Manuf,BB-BONE-PRU-01
<examples> python basic.py 
Traceback (most recent call last):
  File "basic.py", line 1, in <module>
    import beaglebone_pru_adc as adc
  File "/usr/local/lib/python2.7/dist-packages/beaglebone_pru_adc-0.0.3-py2.7-linux-armv7l.egg/beaglebone_pru_adc/__init__.py", line 47, in <module>
    _ensure_adc_loaded()
  File "/usr/local/lib/python2.7/dist-packages/beaglebone_pru_adc-0.0.3-py2.7-linux-armv7l.egg/beaglebone_pru_adc/__init__.py", line 42, in _ensure_adc_loaded
    with open(SLOTS, 'w') as f:
IOError: [Errno 13] Permission denied: '/sys/devices/bone_capemgr.9/slots'
<examples> sudo !!
sudo python basic.py
Traceback (most recent call last):
  File "basic.py", line 1, in <module>
    import beaglebone_pru_adc as adc
  File "/usr/local/lib/python2.7/dist-packages/beaglebone_pru_adc-0.0.3-py2.7-linux-armv7l.egg/beaglebone_pru_adc/__init__.py", line 47, in <module>
    _ensure_adc_loaded()
  File "/usr/local/lib/python2.7/dist-packages/beaglebone_pru_adc-0.0.3-py2.7-linux-armv7l.egg/beaglebone_pru_adc/__init__.py", line 43, in _ensure_adc_loaded
    f.write('BB-ADC')
IOError: [Errno 17] File exists
<examples> ls -l /sys/devices/bone_capemgr.9/slots
-rw-r--r-- 1 root root 4096 Jun  9 00:14 /sys/devices/bone_capemgr.9/slots
<examples>
```

**Comment by martykube** [comment]
Hey, here is the python version I'm using:

```
<tmp> python
Python 2.7.3 (default, Mar 14 2014, 17:55:54)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by pgmmpk** [comment]
Hi Marty,

Just a wild guess. Try rebooting the BB. If you used other libraries (like AdaFruit) to operate ADC or PRU, they may have configured device tree differently. It is a known "feature" that one can not use both AdaFruit and beaglebone_pru_adc (need reboot between switching from one to another).

Let me know how it goes,
-Mike

**Comment by martykube** [comment]
For a wild guess, that was pretty freaking accurate!  This is my first encounter with the device tree so I'm sure it would have taken a while to sort it out.

It sounds like the feature is the don't share the pins. 

Here is the Adafruit library:

```
<~> sudo cat /sys/devices/bone_capemgr.9/slots
 0: 54:PF--- 
 1: 55:PF--- 
 2: 56:PF--- 
 3: 57:PF--- 
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
<~> sudo python
Python 2.7.3 (default, Mar 14 2014, 17:55:54) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Adafruit_BBIO.PWM as PWM
>>> PWM.start('P9_16', 10)
>>> quit()
<~> sudo cat /sys/devices/bone_capemgr.9/slots
 0: 54:PF--- 
 1: 55:PF--- 
 2: 56:PF--- 
 3: 57:PF--- 
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
 7: ff:P-O-L Override Board Name,00A0,Override Manuf,am33xx_pwm
 8: ff:P-O-L Override Board Name,00A0,Override Manuf,bone_pwm_P9_16
```
